# Form implementation generated from reading ui file 'C:\Users\HP\Documents\GitHub\SSIS - Copy\ui\editProgram.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditProgramDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(247, 230)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.editProgram = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.editProgram.setFont(font)
        self.editProgram.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.editProgram.setObjectName("editProgram")
        self.verticalLayout_2.addWidget(self.editProgram)
        self.frame_3 = QtWidgets.QFrame(parent=Dialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.programNameInput = QtWidgets.QLineEdit(parent=self.frame_3)
        self.programNameInput.setText("")
        self.programNameInput.setObjectName("programNameInput")
        self.verticalLayout_3.addWidget(self.programNameInput)
        self.programCodeInput = QtWidgets.QLineEdit(parent=self.frame_3)
        self.programCodeInput.setText("")
        self.programCodeInput.setObjectName("programCodeInput")
        self.verticalLayout_3.addWidget(self.programCodeInput)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(parent=Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.frame_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.collegeInput = QtWidgets.QComboBox(parent=self.frame_2)
        self.collegeInput.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.collegeInput.setEditable(True)
        self.collegeInput.setObjectName("collegeInput")
        self.collegeInput.addItem("")
        self.collegeInput.setItemText(0, "")
        self.horizontalLayout.addWidget(self.collegeInput)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.error = QtWidgets.QLabel(parent=self.frame)
        self.error.setStyleSheet("QLabel{\n"
"    color: red;\n"
"}")
        self.error.setObjectName("error")
        self.verticalLayout.addWidget(self.error)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.save = QtWidgets.QPushButton(parent=self.frame)
        self.save.setObjectName("save")
        self.horizontalLayout_3.addWidget(self.save)
        self.cancel = QtWidgets.QPushButton(parent=self.frame)
        self.cancel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_3.addWidget(self.cancel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.editProgram.setText(_translate("Dialog", "PROGRAM"))
        self.programNameInput.setPlaceholderText(_translate("Dialog", "Program Name"))
        self.programCodeInput.setPlaceholderText(_translate("Dialog", "Program Code"))
        self.label.setText(_translate("Dialog", "College:"))
        self.error.setText(_translate("Dialog", "*Please input all necessary data"))
        self.save.setText(_translate("Dialog", "Save"))
        self.cancel.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
