# Form implementation generated from reading ui file 'C:\Users\HP\Documents\GitHub\SSIS - Copy\ui\editCollege.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditCollegeDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(250, 215)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.editCollege = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.editCollege.setFont(font)
        self.editCollege.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.editCollege.setObjectName("editCollege")
        self.verticalLayout_2.addWidget(self.editCollege)
        self.frame_2 = QtWidgets.QFrame(parent=Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.collegeNameInput = QtWidgets.QLineEdit(parent=self.frame_2)
        self.collegeNameInput.setText("")
        self.collegeNameInput.setObjectName("collegeNameInput")
        self.verticalLayout_3.addWidget(self.collegeNameInput)
        self.collegeCodeInput = QtWidgets.QLineEdit(parent=self.frame_2)
        self.collegeCodeInput.setText("")
        self.collegeCodeInput.setObjectName("collegeCodeInput")
        self.verticalLayout_3.addWidget(self.collegeCodeInput)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.error = QtWidgets.QLabel(parent=self.frame)
        self.error.setStyleSheet("QLabel{\n"
"    color: red;\n"
"}\n"
"")
        self.error.setObjectName("error")
        self.verticalLayout.addWidget(self.error)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.save = QtWidgets.QPushButton(parent=self.frame)
        self.save.setObjectName("save")
        self.horizontalLayout_5.addWidget(self.save)
        self.cancel = QtWidgets.QPushButton(parent=self.frame)
        self.cancel.setObjectName("cancel")
        self.horizontalLayout_5.addWidget(self.cancel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.frame)
        self.verticalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.setStretch(2, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.editCollege.setText(_translate("Dialog", "COLLEGE"))
        self.collegeNameInput.setPlaceholderText(_translate("Dialog", "College Name"))
        self.collegeCodeInput.setPlaceholderText(_translate("Dialog", "College Code"))
        self.error.setText(_translate("Dialog", "*Please input all necessary data"))
        self.save.setText(_translate("Dialog", "Save"))
        self.cancel.setText(_translate("Dialog", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
