# Form implementation generated from reading ui file 'C:\Users\HP\Documents\GitHub\SSIS - Copy\ui\mainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 746)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color: rgb(232, 232, 232);\n"
"}\n"
"\n"
"QTableWidget {\n"
"    background-color: #fff;\n"
"    border: none;\n"
"    gridline-color: #ddd;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #f2f2f2;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    padding: 10px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(1120, 746))
        self.centralwidget.setStyleSheet("QFrame#tables, QFrame#stats {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header_2 = QtWidgets.QVBoxLayout()
        self.header_2.setObjectName("header_2")
        self.header = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.header.setFont(font)
        self.header.setStyleSheet("QFrame{\n"
"    background-color: rgb(85, 0, 0);\n"
"}")
        self.header.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.header.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.header.setObjectName("header")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.header)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(parent=self.header)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    color: white;\n"
"    border: none;\n"
"    margin-left: 20px;\n"
"}")
        self.label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.header_2.addWidget(self.header)
        self.verticalLayout_2.addLayout(self.header_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.verticalLayout.setContentsMargins(20, 10, 20, 30)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stats = QtWidgets.QFrame(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stats.sizePolicy().hasHeightForWidth())
        self.stats.setSizePolicy(sizePolicy)
        self.stats.setStyleSheet("QFrame #welcome{\n"
"    background-color: #fff;       \n"
"    border: 1px solid #ddd;       \n"
"    border-radius: 20px;    \n"
"    padding: 10px;             \n"
"}\n"
"\n"
"QLabel{\n"
"    font-weight: bold;\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"")
        self.stats.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.stats.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.stats.setObjectName("stats")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.stats)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.studentCount = QtWidgets.QLabel(parent=self.stats)
        self.studentCount.setObjectName("studentCount")
        self.horizontalLayout.addWidget(self.studentCount)
        self.programCount = QtWidgets.QLabel(parent=self.stats)
        self.programCount.setObjectName("programCount")
        self.horizontalLayout.addWidget(self.programCount)
        self.collegeCount = QtWidgets.QLabel(parent=self.stats)
        self.collegeCount.setObjectName("collegeCount")
        self.horizontalLayout.addWidget(self.collegeCount)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.stats)
        self.tables = QtWidgets.QFrame(parent=self.centralwidget)
        self.tables.setStyleSheet("QHeaderView::section, QTableWidget::item {\n"
"    border-bottom: 1px solid rgb(85, 0, 0);\n"
"}\n"
"\n"
"QHeaderView::section:last{\n"
"    color:transparent;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    background: white;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: lightblue;\n"
"    color: rgb(85, 0, 0);\n"
"}\n"
"\n"
"QTableWidget::item:hover {\n"
"    background-color: lightblue;\n"
"    color: rgb(85, 0, 0);\n"
"}\n"
"\n"
"QTableWidget::row:hover {\n"
"    background-color: lightblue;\n"
"    color: rgb(85, 0, 0);\n"
"}\n"
"")
        self.tables.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tables.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tables.setObjectName("tables")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tables)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.functions = QtWidgets.QHBoxLayout()
        self.functions.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.functions.setSpacing(1)
        self.functions.setObjectName("functions")
        self.sortBy = QtWidgets.QComboBox(parent=self.tables)
        self.sortBy.setObjectName("sortBy")
        self.sortBy.addItem("")
        self.functions.addWidget(self.sortBy)
        self.sortOrder = QtWidgets.QComboBox(parent=self.tables)
        self.sortOrder.setObjectName("sortOrder")
        self.sortOrder.addItem("")
        self.sortOrder.addItem("")
        self.sortOrder.addItem("")
        self.functions.addWidget(self.sortOrder)
        self.addButton = QtWidgets.QPushButton(parent=self.tables)
        self.addButton.setObjectName("addButton")
        self.functions.addWidget(self.addButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.functions.addItem(spacerItem)
        self.searchBy = QtWidgets.QComboBox(parent=self.tables)
        self.searchBy.setStyleSheet("")
        self.searchBy.setEditable(False)
        self.searchBy.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.NoInsert)
        self.searchBy.setObjectName("searchBy")
        self.searchBy.addItem("")
        self.functions.addWidget(self.searchBy)
        self.searchInput = QtWidgets.QLineEdit(parent=self.tables)
        self.searchInput.setObjectName("searchInput")
        self.functions.addWidget(self.searchInput)
        self.verticalLayout_3.addLayout(self.functions)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.tables)
        self.tabWidget.setStyleSheet("QTabBar::tab {\n"
"    background: white;\n"
"    border: 1px solid #ccc;\n"
"    border-top-left-radius: 5px;\n"
"    border-top-right-radius: 5px;\n"
"    padding: 8px 15px;\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: #f5f5f5;\n"
"    border: 1px solid #ccc;\n"
"    border-bottom: none;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    border: 1px solid #ccc;\n"
"    top: -1px;\n"
"}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.studentsTable = QtWidgets.QTableWidget(parent=self.tab)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.studentsTable.setFont(font)
        self.studentsTable.setMouseTracking(True)
        self.studentsTable.setStyleSheet("")
        self.studentsTable.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Javanese, QtCore.QLocale.Country.Indonesia))
        self.studentsTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.studentsTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.studentsTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.studentsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.studentsTable.setTextElideMode(QtCore.Qt.TextElideMode.ElideNone)
        self.studentsTable.setShowGrid(False)
        self.studentsTable.setGridStyle(QtCore.Qt.PenStyle.NoPen)
        self.studentsTable.setColumnCount(7)
        self.studentsTable.setObjectName("studentsTable")
        self.studentsTable.setRowCount(0)
        self.studentsTable.horizontalHeader().setStretchLastSection(False)
        self.studentsTable.verticalHeader().setVisible(False)
        self.studentsTable.verticalHeader().setDefaultSectionSize(40)
        self.studentsTable.verticalHeader().setHighlightSections(False)
        self.horizontalLayout_3.addWidget(self.studentsTable)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.programsTable = QtWidgets.QTableWidget(parent=self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.programsTable.setFont(font)
        self.programsTable.setMouseTracking(True)
        self.programsTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.programsTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.programsTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.programsTable.setShowGrid(False)
        self.programsTable.setGridStyle(QtCore.Qt.PenStyle.NoPen)
        self.programsTable.setColumnCount(4)
        self.programsTable.setObjectName("programsTable")
        self.programsTable.setRowCount(0)
        self.programsTable.horizontalHeader().setStretchLastSection(False)
        self.programsTable.verticalHeader().setVisible(False)
        self.programsTable.verticalHeader().setDefaultSectionSize(40)
        self.programsTable.verticalHeader().setHighlightSections(False)
        self.horizontalLayout_5.addWidget(self.programsTable)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.collegesTable = QtWidgets.QTableWidget(parent=self.tab_3)
        self.collegesTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.collegesTable.setFont(font)
        self.collegesTable.setMouseTracking(True)
        self.collegesTable.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.collegesTable.setStyleSheet("")
        self.collegesTable.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Konkani, QtCore.QLocale.Country.India))
        self.collegesTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.collegesTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.collegesTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.collegesTable.setShowGrid(False)
        self.collegesTable.setGridStyle(QtCore.Qt.PenStyle.NoPen)
        self.collegesTable.setColumnCount(3)
        self.collegesTable.setObjectName("collegesTable")
        self.collegesTable.setRowCount(0)
        self.collegesTable.horizontalHeader().setDefaultSectionSize(150)
        self.collegesTable.horizontalHeader().setStretchLastSection(False)
        self.collegesTable.verticalHeader().setVisible(False)
        self.collegesTable.verticalHeader().setDefaultSectionSize(40)
        self.collegesTable.verticalHeader().setHighlightSections(False)
        self.horizontalLayout_6.addWidget(self.collegesTable)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.frame = QtWidgets.QFrame(parent=self.tables)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.firstPageButton = QtWidgets.QPushButton(parent=self.frame)
        self.firstPageButton.setObjectName("firstPageButton")
        self.horizontalLayout_4.addWidget(self.firstPageButton)
        self.previousButton = QtWidgets.QPushButton(parent=self.frame)
        self.previousButton.setObjectName("previousButton")
        self.horizontalLayout_4.addWidget(self.previousButton)
        self.pageInfo = QtWidgets.QLabel(parent=self.frame)
        self.pageInfo.setObjectName("pageInfo")
        self.horizontalLayout_4.addWidget(self.pageInfo)
        self.nextButton = QtWidgets.QPushButton(parent=self.frame)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout_4.addWidget(self.nextButton)
        self.lastPageButton = QtWidgets.QPushButton(parent=self.frame)
        self.lastPageButton.setObjectName("lastPageButton")
        self.horizontalLayout_4.addWidget(self.lastPageButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.frame)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 11)
        self.verticalLayout.addWidget(self.tables)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 10)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 11)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Student Information System"))
        self.studentCount.setText(_translate("MainWindow", "TextLabel"))
        self.programCount.setText(_translate("MainWindow", "TextLabel"))
        self.collegeCount.setText(_translate("MainWindow", "TextLabel"))
        self.sortBy.setItemText(0, _translate("MainWindow", "Sort By..."))
        self.sortOrder.setItemText(0, _translate("MainWindow", "Order..."))
        self.sortOrder.setItemText(1, _translate("MainWindow", "Ascending"))
        self.sortOrder.setItemText(2, _translate("MainWindow", "Descending"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.searchBy.setItemText(0, _translate("MainWindow", "Search All"))
        self.searchInput.setPlaceholderText(_translate("MainWindow", "Search..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Students"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Programs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Colleges"))
        self.firstPageButton.setText(_translate("MainWindow", "First Page"))
        self.previousButton.setText(_translate("MainWindow", "Previous"))
        self.pageInfo.setText(_translate("MainWindow", "TextLabel"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
        self.lastPageButton.setText(_translate("MainWindow", "Last Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
